version: '3.7'
services:

    web:
        build:
            context: ./
            dockerfile: ./dockerConfig/web.docker
        container_name: web
        volumes:
            - ./app:/var/www:cached
        ports:
            - "80:80"
        links:
            - app

    app:
        build:
            context: ./
            dockerfile: ./dockerConfig/app.docker
        container_name: app
        volumes:
            - ./app:/var/www:cached
        links:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: database        
        environment:
            - "MYSQL_ROOT_PASSWORD=test"
            - "MYSQL_DATABASE=test"
        ports:
            - "3306:3306"